FROM python:3.13-slim
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY alembic.ini .
COPY alembic ./alembic
COPY entrypoint.sh .
COPY app ./app

ENV PYTHONUNBUFFERED=1
EXPOSE 8000

CMD ["sh","entrypoint.sh"]
