FROM ghcr.io/cirruslabs/flutter:stable AS build
WORKDIR /app
COPY pubspec.yaml pubspec.lock* ./
RUN flutter pub get
COPY . .
RUN flutter create --platforms=web . && flutter pub get && flutter build web --release --dart-define=API_BASE_URL=https://wazen-api-production-ee44.up.railway.app/api/v1

FROM nginx:alpine
COPY --from=build /app/build/web /usr/share/nginx/html
RUN printf 'server { listen 8080; root /usr/share/nginx/html; index index.html; location / { try_files $uri $uri/ /index.html; } }' > /etc/nginx/conf.d/default.conf
EXPOSE 8080
CMD ["nginx","-g","daemon off;"]
